2024-06-04 19:47:30.349 | ERROR    | __main__:<module>:35 - Error while starting bot [app - runner.py]
Traceback (most recent call last):

> File "F:\Projects\TelegramTrader\app\runner.py", line 31, in <module>
    metaTraderSettings = cfg.MetaTrader
                         └ <JSONConfiguration: 0x2622937ba90>

  File "C:\Python310\lib\site-packages\config\configuration.py", line 176, in __getattr__
    raise AttributeError(item) from None
                         └ 'MetaTrader'

AttributeError: MetaTrader
