2024-06-04 19:48:09.467 | ERROR    | __main__:<module>:35 - Error while starting bot [app - runner.py]
Traceback (most recent call last):

> File "F:\Projects\TelegramTrader\app\runner.py", line 33, in <module>
    telegram = Telegram(telegramSettings.api_id, telegramSettings.api_hash)
               │        │                        └ <Configuration: 0x1932010b460>
               │        └ <Configuration: 0x1932010b460>
               └ <module 'Telegram' from 'F:\\Projects\\TelegramTrader\\app\\Telegram\\__init__.py'>

TypeError: 'module' object is not callable
